### ISSUE TITLE
wordcloud|add|Pokémon

### ISSUE THREAD

**Issue by TurnipGuy30** [JessicaLim8/JessicaLim8#616]
Just replace <INSERT-WORD> with your word - don't remove the `wordcloud|add|`   
Next click 'Submit new issue'

**Note: Please give the wordcloud a few minutes to update as Github sometimes caches images :hourglass:**  
Don't worry, if your word is not properly added, a comment will be added to this issue

**Code of Conduct:**  
- Please do not blatantly self promote (i.e. constantly spam-add your own name)
- No swearing, insults or inappropriate content
- Try to answer the prompt but most of all, have fun!

**Comment by Isabel-Lifu-211207-XPrado** [comment]
> Just replace with your word - don't remove the `wordcloud|add|`
> Next click 'Submit new issue'
> 
> **Note: Please give the wordcloud a few minutes to update as Github sometimes caches images ⌛**
> Don't worry, if your word is not properly added, a comment will be added to this issue
> 
> **Code of Conduct:**
> 
> * Please do not blatantly self promote (i.e. constantly spam-add your own name)
> * No swearing, insults or inappropriate content
> * Try to answer the prompt but most of all, have fun!

You're a pro at using Github's issues to help people with their codes/programs! Great job!
